DROPDOWN_VALUES = {
    "countries": [
        "United Kingdom",
        "United States",
        "Albania",
        "Andorra",
        "Austria",
        "Belarus",
        "Belgium",
        "Bosnia and Herzegovina",
        "Bulgaria",
        "Croatia",
        "Cyprus",
        "Czechia",
        "Denmark",
        "Estonia",
        "Finland",
        "France",
        "Germany",
        "Greece",
        "Hungary",
        "Iceland",
        "Ireland",
        "Italy",
        "Kosovo",
        "Latvia",
        "Liechtenstein",
        "Lithuania",
        "Luxembourg",
        "Malta",
        "Moldova",
        "Monaco",
        "Montenegro",
        "Netherlands",
        "North Macedonia",
        "Norway",
        "Poland",
        "Portugal",
        "Romania",
        "Russia",
        "San Marino",
        "Serbia",
        "Slovakia",
        "Slovenia",
        "Spain",
        "Sweden",
        "Switzerland",
        "Turkey",
        "Ukraine",
        "Vatican City",
    ],
    "account_tiers": [
        "1",
        "2",
        "3",
    ],
    "contact_categories": [
        "Executive",
        "Business",
        "Technical",
        "Procurement",
        "Security",
        "Project/Programme Management",
    ],
    "bmc_relationships": [
        "Champion",
        "Coach",
        "Lead",
        "Influencer",
        "Executive Buyer",
        "Executive Assistant",
        "Detractor",
    ],
    "partner_involvement_statuses": [
        "Target Partner",
        "Introduced",
        "Engaged",
        "Active",
        "Dormant",
        "Not Relevant",
    ],
    "suggested_partner_names": [
        "AWS",
        "Computacenter",
        "Trustmarque",
        "Capgemini",
        "ATOS",
        "Accenture",
    ],
    "partner_types": [
        "GOSI",
        "Reseller",
        "Partner",
        "Hyperscaler",
    ],
    "partner_contact_roles": [
        "Account Manager",
        "Solution Engineer",
        "Presales",
        "CTO",
        "CIO",
        "CEO",
        "Director",
        "Technical Analyst",
    ],
    "partner_engagement_statuses": [
        "New",
        "Warm Intro",
        "Engaged",
        "Active Collaborator",
        "Dormant",
        "Not Relevant",
    ],
    "quarters": [
        "Q1",
        "Q2",
        "Q3",
        "Q4",
    ],
    "outreach_activity_types": [
        "VITO",
        "LinkedIn",
        "Phone",
        "White Paper / Webinar / Consensus",
        "Events",
        "Email",
        "Meeting",
        "Follow-up",
        "Partner Touchpoint",
        "Other",
    ],
    "outreach_campaigns": [
        "VITO",
        "LinkedIn",
        "Calls",
        "White Paper / Webinar / Consensus",
        "Events",
    ],
    "outreach_outcomes": [
        "No Response",
        "Positive Response",
        "Neutral Response",
        "Negative Response",
        "Meeting Booked",
        "NBM Booked",
        "Discovery Booked",
        "Exec Meeting Booked",
        "Webinar Attended",
        "Consensus Viewed",
        "Referral Made",
        "Not Relevant",
        "Follow-up Required",
    ],
    "task_statuses": [
        "Not Started",
        "In Progress",
        "Pending",
        "Closed",
        "Completed",
        "Cancelled",
    ],
}
